monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                #path: php://stderr
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: [ "!event", "!doctrine" ]

when@prod:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: [ "!event", "!doctrine" ]
