nelmio_api_doc:
    documentation:
        info:
            title: Library API
            description: API for adding storage and retrieval of books in the library
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
